import db.MalleDB;
import file.FileManager;
import util.Options;

import java.io.File;
import java.io.IOException;

public class fileManage {
    public static void main(String[] args) throws IOException {
        MalleDB malleDB = new MalleDB();
        malleDB.init(new Options(Options.DB_TYPE.MYSQL));

        FileManager fileManager = new FileManager(malleDB);

        //fileManager.insertFile2("C:\\rrr\\fl1.txt");
        fileManager.readFile("Meta_20210507152143fl1.txt");    // Key is AutoGenerated : (TIME) + (FILEID)
       // fileManager.deleteFile("20210427220952toeic.jpg");
    }
}
